on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - 'release/*' # Create when a new release branch is pushed

name: Create Draft Release

jobs:
  build:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn install

      - name: Generate changelog
        run: |
          if [[ -f changelog_tmp ]]; then; rm changelog_tmp; fi;
          ./node_modules/.bin/standard-version -i changelog_tmp

      - name: Read changelog
        id: readfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.readfile.outputs.content }}
          draft: true
          prerelease: false
