on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Draft Release

jobs:
  build:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: yarn install

      - name: Generate changelog
        run: |
          echo "" > changelog_tmp
          ./node_modules/.bin/standard-version -i changelog_tmp --skip.commit --skip.tag --header ""

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          bodyFile: changelog_tmp
          draft: true
          prerelease: false
